# Generated by Django 2.2 on 2023-03-16 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsfw', models.BooleanField()),
                ('religious', models.BooleanField()),
                ('political', models.BooleanField()),
                ('racist', models.BooleanField()),
                ('sexist', models.BooleanField()),
                ('explicit', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('setup', models.CharField(max_length=500)),
                ('delivery', models.CharField(max_length=500)),
                ('safe', models.BooleanField()),
                ('joke_id', models.IntegerField()),
                ('flags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Flags')),
            ],
        ),
    ]
