# Generated by Django 2.2 on 2023-03-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_flags_joke'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joke',
            name='flags',
        ),
        migrations.AddField(
            model_name='joke',
            name='explicit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joke',
            name='joke',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='joke',
            name='lang',
            field=models.CharField(default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='joke',
            name='nsfw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joke',
            name='political',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joke',
            name='racist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joke',
            name='religious',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joke',
            name='sexist',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='joke',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='joke',
            name='delivery',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='joke',
            name='joke_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='joke',
            name='safe',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='joke',
            name='setup',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='joke',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Flags',
        ),
    ]
