# Generated by Django 2.2 on 2023-03-23 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20230323_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joke',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='joke',
            name='explicit',
        ),
        migrations.RemoveField(
            model_name='joke',
            name='joke',
        ),
        migrations.RemoveField(
            model_name='joke',
            name='joke_id',
        ),
        migrations.RemoveField(
            model_name='joke',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='joke',
            name='nsfw',
        ),
        migrations.RemoveField(
            model_name='joke',
            name='political',
        ),
        migrations.RemoveField(
            model_name='joke',
            name='racist',
        ),
        migrations.RemoveField(
            model_name='joke',
            name='religious',
        ),
        migrations.RemoveField(
            model_name='joke',
            name='safe',
        ),
        migrations.RemoveField(
            model_name='joke',
            name='setup',
        ),
        migrations.RemoveField(
            model_name='joke',
            name='sexist',
        ),
        migrations.RemoveField(
            model_name='joke',
            name='type',
        ),
    ]
