# Generated by Django 4.1.7 on 2023-03-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_joke_joke'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='delivery',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='joke',
            name='explicit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joke',
            name='joke_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joke',
            name='lang',
            field=models.CharField(default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='joke',
            name='nsfw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joke',
            name='political',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joke',
            name='racist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joke',
            name='religious',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joke',
            name='safe',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='joke',
            name='setup',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='joke',
            name='sexist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joke',
            name='type',
            field=models.CharField(default='single', max_length=255),
        ),
        migrations.AlterField(
            model_name='joke',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
