# Generated by Django 4.1.7 on 2023-03-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_joke_delivery_joke_explicit_joke_joke_id_joke_lang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='joke',
            field=models.TextField(default='', null=True),
        ),
    ]
